# Generated by Django 5.2.7 on 2025-11-07 03:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='pin',
            field=models.CharField(default='000000', editable=False, help_text='Human-friendly PIN for students to join (6 digits)', max_length=6, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID for session', unique=True),
        ),
    ]
